### ISSUE TITLE
Set up an github action workflow for phpunit tests and php-cs-linter

### ISSUE THREAD

**Issue by Tjoosten** [Activisme-be/Ragnarok#10]

**Comment by GueGuerreiro** [comment]
Seems like a good first issue to learn how Github Actions work :) I'll take a crack at it, and go read some docs. If for some reason I find that I can't do it I'll let you know so it can get assigned to someone else.

**Comment by Tjoosten** [comment]
Hey @GueGuerreiro 

Thank u for taking up on this one. As you can see i already tried to implement an action but that failed. So feel free to improve or rewrite the action. 

Also i will assign u for making sure someone doesn't try to steal this issue. If you got any questions feel free to ask.

**Comment by GueGuerreiro** [comment]
I implemented 2 actions, one for PHPCS and another one for PHPUnit.

I used 2 existing marketplace actions:
- [rtCamp/action-phpcs-code-review](https://github.com/rtCamp/action-phpcs-code-review)
- [nathanheffley/laravel-phpunit-action](https://github.com/nathanheffley/laravel-phpunit-action)

And I set them up to run checks for every pull request. You can see them in action here, in this test PR I made: https://github.com/GueGuerreiro/Ragnarok/pull/1

A couple of notes:

- The PHPCS action I used (Which seemed to be the most popular), requires you to set up a bot account. It's not hard to do, and I'll leave the process documented on my PR, but there is that extra step attached to it.
- The PHPCS action also advises to disable direct commiting to the main branch, so we ensure the checks always run for every code change: 

> This action doesn't run for code committed directly to a branch. We highly recommend that you disable direct commits to your main/master branch.

Is this what you were looking for, or did you have something else in mind for this issue?

**Comment by Tjoosten** [comment]
Hey @GueGuerreiro 

It looks good. But by reading  through the steps on the actions. I see some errors remaining in the output. 
Would u like to debug and fix these? If not. That's ok. 

Kind regards, 
Tim Joosten

**Comment by GueGuerreiro** [comment]
Hey @Tjoosten :) Appreciate the sentiment on the edit, but no harm done. I didn't take it the wrong way at all. Apologies for the late reply, as I just recently got off of work.

I saw one test with a warning on the debug messages and thought that was why the check failed. But reading your message and scrolling a bit up it seems that this was a problem with MySQL not being set up correctly.

I removed the nathanheffley/laravel-phpunit-action action and set up my own job with a MySQL service attached. I had to play around with it a bit to figure out why it wasn't working, but I got it to run the PHPUnit tests successfully now:  https://github.com/GueGuerreiro/Ragnarok/pull/7/ :tada: 

I'll send in a PR soon with the instructions to set up the PHPCS action bot included :+1:

**Comment by Tjoosten** [comment]
Hey @GueGuerreiro. No problem take your time. Thanks for the effort

**Comment by GueGuerreiro** [comment]
PR opened and linked here :tada: Thanks for letting me work on this issue :smile:

**Comment by Tjoosten** [comment]
No you thank u for all your effort in this one. Hope u learned something on the way :) 

But leaving this for myself here. https://stackoverflow.com/questions/38445289/how-to-create-a-new-github-account-with-the-same-email-address 

Will take a deeper dive into this PR tomorrow
